  name: zad
  description: "A new Flutter project."
  publish_to: 'none'

  version: 1.0.0+1

  environment:
    sdk: ^3.10.7

  dependencies:
    flutter:
      sdk: flutter

    cupertino_icons: ^1.0.8
    http: ^1.6.0
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    flutter_compass: ^0.8.1
    geolocator: ^14.0.3
    share_plus: ^13.3.0
    flutter_local_notifications: ^22.3.0
    timezone: ^0.11.1
    flutter_timezone: ^5.1.0

  dev_dependencies:
    flutter_test:
      sdk: flutter

    flutter_lints: ^6.0.0
    flutter_launcher_icons: ^0.14.4

  flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/icons/icon_app/zad_icon.jpg"

  flutter:
    uses-material-design: true

    assets:
      - assets/azkar/azkar.json
